CI: fedora rawhide follow up
libressl/portable pull request #902
Opened 2023-08-18 05:15 UTC by chipitsine

2023-08-18 05:47 UTC, botovq requested changes

2023-08-18 05:47 UTC, botovq commented on .github/workflows/fedora-rawhide.yml
>          ./configure
The `./configure` step is not needed for cmake builds.

(I also think `./autogen.sh` isn't really needed and `./update.sh` would be good enough, but let's leave it like that for now).

2023-08-18 05:47 UTC, botovq commented on .github/workflows/fedora-rawhide.yml
> +
zap trailinig empty line, please

2023-08-18 18:02 UTC, merged

2024-07-07 14:46 UTC, botovq commented
This workflow now fails to install the deps [with][1]

```
  file /usr/lib64/libimaevm.so.4.0.0 from install of ima-evm-utils-libs-1.6-0.fc41.x86_64 conflicts with file from package ima-evm-utils-1.5-4.fc40.x86_64
```

Before I waste a lot of time poking at an OS I don't know, do you perhaps know how to fix this?

Cc @joshuasing 

[1]: https://github.com/libressl/portable/actions/runs/9815355271/job/27104270522#step:4:355

2024-07-07 14:52 UTC, chipitsine commented
it happens from time to time on Rawhide, usually it is resolved by itself in several days
I'll check.

2024-07-07 14:56 UTC, joshuasing commented
> This workflow now fails to install the deps [with](https://github.com/libressl/portable/actions/runs/9815355271/job/27104270522#step:4:355)
> 
> ```
>   file /usr/lib64/libimaevm.so.4.0.0 from install of ima-evm-utils-libs-1.6-0.fc41.x86_64 conflicts with file from package ima-evm-utils-1.5-4.fc40.x86_64
> ```
> 
> Before I waste a lot of time poking at an OS I don't know, do you perhaps know how to fix this?
> 
> Cc @joshuasing

I don't use `dnf` very often, so I'm not sure what would cause this, but I can look into it.
If @chipitsine knows anything, that would be great, otherwise I'll also have a look to try and find a solution.

2024-07-08 03:31 UTC, botovq commented
On Sun, Jul 07, 2024 at 07:53:05AM -0700, Ilya Shipitsin wrote:
> it happens from time to time on Rawhide, usually it is resolved by itself in several days

Seems to have fixed itself (presumably some packaging error).

Thanks!

2024-07-08 07:13 UTC, chipitsine commented
the benefit of using Fedora |Rawhide is the most recent gcc and clang. The price however is stability